spring:
  application:
    name: Hostels

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jwt:
    secret: ${JWT_SECRET_KEY}
    expirationInMinutes: ${JWT_EXPIRATION_MINUTES}
